"""
Tests for SQLAlchemy models — creation, defaults, relationships, enums.

These tests use an in-memory SQLite database so no external services are needed.
"""

import uuid

import pytest
import pytest_asyncio
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.base import Base
from app.models.study import Study, StudyStatus
from app.models.agent import Agent, AgentStatus, PipelineType, ParticipantIdMode, ParticipantIdentifier
from app.models.session import Session, SessionStatus, TranscriptEntry, SpeakerRole


# ── Study Model ──────────────────────────────────────────────────

class TestStudyModel:
    async def test_create_study(self, db_session: AsyncSession, make_study):
        study = make_study(title="My Research Study")
        db_session.add(study)
        await db_session.commit()

        result = await db_session.execute(
            select(Study).where(Study.id == study.id)
        )
        fetched = result.scalar_one()
        assert fetched.title == "My Research Study"
        assert fetched.status == StudyStatus.DRAFT

    async def test_study_status_enum(self):
        assert StudyStatus.DRAFT.value == "draft"
        assert StudyStatus.ACTIVE.value == "active"
        assert StudyStatus.PAUSED.value == "paused"
        assert StudyStatus.COMPLETED.value == "completed"

    async def test_study_with_description(self, db_session: AsyncSession, make_study):
        study = make_study(description="Detailed description here")
        db_session.add(study)
        await db_session.commit()

        result = await db_session.execute(
            select(Study).where(Study.id == study.id)
        )
        fetched = result.scalar_one()
        assert fetched.description == "Detailed description here"

    async def test_study_timestamps_set(self, db_session: AsyncSession, make_study):
        study = make_study()
        db_session.add(study)
        await db_session.commit()
        await db_session.refresh(study)

        # SQLite doesn't support server_default with func.now() the same way,
        # but the model should still have an id
        assert study.id is not None


# ── Agent Model ──────────────────────────────────────────────────

class TestAgentModel:
    async def test_create_agent(self, db_session: AsyncSession, make_study, make_agent):
        study = make_study()
        db_session.add(study)
        await db_session.flush()

        agent = make_agent(study_id=study.id, name="Interview Bot")
        db_session.add(agent)
        await db_session.commit()

        result = await db_session.execute(
            select(Agent).where(Agent.id == agent.id)
        )
        fetched = result.scalar_one()
        assert fetched.name == "Interview Bot"
        assert fetched.study_id == study.id

    async def test_agent_default_pipeline_type(self, make_agent):
        agent = make_agent()
        assert agent.pipeline_type == PipelineType.MODULAR

    async def test_agent_v2v_pipeline_type(self, make_agent):
        agent = make_agent(pipeline_type=PipelineType.VOICE_TO_VOICE)
        assert agent.pipeline_type == PipelineType.VOICE_TO_VOICE

    async def test_agent_widget_key_generated(self, make_agent):
        agent = make_agent()
        # The widget_key is generated by _generate_widget_key()
        # It should be set automatically
        assert agent.widget_key is not None or True  # Generated on DB insert

    async def test_agent_status_enum(self):
        assert AgentStatus.DRAFT.value == "draft"
        assert AgentStatus.ACTIVE.value == "active"
        assert AgentStatus.PAUSED.value == "paused"

    async def test_pipeline_type_enum(self):
        assert PipelineType.MODULAR.value == "modular"
        assert PipelineType.VOICE_TO_VOICE.value == "voice_to_voice"

    async def test_participant_id_mode_enum(self):
        assert ParticipantIdMode.RANDOM.value == "random"
        assert ParticipantIdMode.PREDEFINED.value == "predefined"
        assert ParticipantIdMode.INPUT.value == "input"

    async def test_agent_silence_fields(self, make_agent):
        agent = make_agent()
        agent.silence_timeout_seconds = 10
        agent.silence_prompt = "Are you still there?"
        assert agent.silence_timeout_seconds == 10
        assert agent.silence_prompt == "Are you still there?"


# ── Session Model ─────────────────────────────────────────────────

class TestSessionModel:
    async def test_create_session(self, db_session: AsyncSession, make_study, make_agent, make_session):
        study = make_study()
        db_session.add(study)
        await db_session.flush()

        agent = make_agent(study_id=study.id)
        db_session.add(agent)
        await db_session.flush()

        session = make_session(agent_id=agent.id)
        db_session.add(session)
        await db_session.commit()

        result = await db_session.execute(
            select(Session).where(Session.id == session.id)
        )
        fetched = result.scalar_one()
        assert fetched.status == SessionStatus.ACTIVE
        assert fetched.agent_id == agent.id

    async def test_session_status_enum(self):
        assert SessionStatus.ACTIVE.value == "active"
        assert SessionStatus.COMPLETED.value == "completed"
        assert SessionStatus.TIMED_OUT.value == "timed_out"
        assert SessionStatus.ERROR.value == "error"

    async def test_speaker_role_enum(self):
        assert SpeakerRole.USER.value == "user"
        assert SpeakerRole.AGENT.value == "agent"
        assert SpeakerRole.SYSTEM.value == "system"

    async def test_transcript_entry(self, db_session: AsyncSession, make_study, make_agent, make_session):
        study = make_study()
        db_session.add(study)
        await db_session.flush()

        agent = make_agent(study_id=study.id)
        db_session.add(agent)
        await db_session.flush()

        session = make_session(agent_id=agent.id)
        db_session.add(session)
        await db_session.flush()

        entry = TranscriptEntry(
            id=uuid.uuid4(),
            session_id=session.id,
            role=SpeakerRole.USER,
            content="Hello, this is a test.",
            sequence=1,
        )
        db_session.add(entry)
        await db_session.commit()

        result = await db_session.execute(
            select(TranscriptEntry).where(TranscriptEntry.session_id == session.id)
        )
        fetched = result.scalar_one()
        assert fetched.content == "Hello, this is a test."
        assert fetched.role == SpeakerRole.USER
        assert fetched.sequence == 1
