"""add widget config participant ids

Revision ID: 2bdd8f712d28
Revises: af8324aeafb6
Create Date: 2026-03-13 21:29:09.369603
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bdd8f712d28'
down_revision: Union[str, None] = 'af8324aeafb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create the enum type first
    participant_id_mode_enum = sa.Enum('random', 'predefined', 'input', name='participant_id_mode')
    participant_id_mode_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('participant_identifiers',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('used', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('agents', sa.Column('participant_id_mode', participant_id_mode_enum, server_default='random', nullable=False))
    op.add_column('agents', sa.Column('widget_title', sa.String(length=255), nullable=True))
    op.add_column('agents', sa.Column('widget_description', sa.Text(), nullable=True))
    op.add_column('agents', sa.Column('widget_primary_color', sa.String(length=20), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'widget_primary_color')
    op.drop_column('agents', 'widget_description')
    op.drop_column('agents', 'widget_title')
    op.drop_column('agents', 'participant_id_mode')
    op.drop_table('participant_identifiers')
    # ### end Alembic commands ###
