"""add_widget_listening_message

Revision ID: 4a07d0afd329
Revises: 2bdd8f712d28
Create Date: 2026-03-14 02:02:35.969587
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a07d0afd329'
down_revision: Union[str, None] = '2bdd8f712d28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('widget_listening_message', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'widget_listening_message')
    # ### end Alembic commands ###
