"""create studies and agents tables

Revision ID: 53b7bae909ec
Revises: 
Create Date: 2026-03-13 19:56:02.786834
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53b7bae909ec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studies',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'paused', 'completed', name='study_status'), server_default='draft', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agents',
    sa.Column('study_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'paused', name='agent_status'), server_default='draft', nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('welcome_message', sa.Text(), nullable=True),
    sa.Column('pipeline_type', sa.Enum('modular', 'voice_to_voice', name='pipeline_type'), server_default='modular', nullable=False),
    sa.Column('llm_model', sa.String(length=255), nullable=False),
    sa.Column('stt_provider', sa.String(length=100), nullable=False),
    sa.Column('stt_model', sa.String(length=100), nullable=True),
    sa.Column('tts_provider', sa.String(length=100), nullable=False),
    sa.Column('tts_model', sa.String(length=100), nullable=True),
    sa.Column('tts_voice', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=10), server_default='en', nullable=False),
    sa.Column('max_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('widget_key', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('widget_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agents')
    op.drop_table('studies')
    # ### end Alembic commands ###
