"""add_twilio_phone_number

Revision ID: 7e13033c586a
Revises: 4a07d0afd329
Create Date: 2026-03-14 02:16:45.099414
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e13033c586a'
down_revision: Union[str, None] = '4a07d0afd329'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('twilio_phone_number', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'twilio_phone_number')
    # ### end Alembic commands ###
