"""add_silence_handling_fields

Revision ID: 8b30eb23a410
Revises: 93ccd082bff1
Create Date: 2026-03-14 03:06:31.466576
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b30eb23a410'
down_revision: Union[str, None] = '93ccd082bff1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('silence_timeout_seconds', sa.Integer(), nullable=True))
    op.add_column('agents', sa.Column('silence_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'silence_prompt')
    op.drop_column('agents', 'silence_timeout_seconds')
    # ### end Alembic commands ###
